### ISSUE TITLE
Erro no Arquivo "Insert"

### ISSUE THREAD

**Issue by tlbdmecanica** [CampeonatoJJJE/Campeonato#9]
Encontramos um erro no arquivo "Insert.sql", onde o valor do atributo "Num_rodadas" da tabela campeonato é do tipo "Int" mas a inserção está em formado de email (varchar).

![erro](https://user-images.githubusercontent.com/31859118/30552318-f051af38-9c73-11e7-8f4b-45e09b071369.png)
![erro 2](https://user-images.githubusercontent.com/31859118/30552319-f0640c96-9c73-11e7-87cb-35776d28e421.png)
![erro 3](https://user-images.githubusercontent.com/31859118/30552497-8ab1f862-9c74-11e7-9db1-f433c4a2d532.png)

**Comment by bmarchete** [comment]
@CampeonatoJJJE E aí, o grupo vai ficar esperando até amanhã as respostas? 😢

**Comment by CampeonatoJJJE** [comment]
Okay, iremos verificar.

**Comment by tlbdmecanica** [comment]
Encontramos mais três erros no mesmo arquivo ("Insert.sql"), o primeiro é:
Na tabela "Jogadores", há um atributo com nome errado ("codigo_time") o correto seria "times_codigo"

![erro 5](https://user-images.githubusercontent.com/31859118/30554060-960cf752-9c79-11e7-8e04-cebc5b383d3d.png)
![erro 4](https://user-images.githubusercontent.com/31859118/30554061-9634e21c-9c79-11e7-827c-b20980373717.png)

O segundo é:
Na tabela "Pontuacao", há dois atributo com nome errado ("codigo_campeonato" e "codigo_time") o correto seria "campeonato_codigo" e "times_codigo".

![erro 6](https://user-images.githubusercontent.com/31859118/30554102-c729321a-9c79-11e7-83b0-0a98817137d5.png)
![erro 7](https://user-images.githubusercontent.com/31859118/30554103-c72e43e0-9c79-11e7-8f59-955de6cde965.png)

O terceiro é:
Na tabela times, o valor para o campo "data_criacao" está no formato errado, o correto seria "Ano-Mês-Dia".

![erro 8](https://user-images.githubusercontent.com/31859118/30554149-e93c1ea8-9c79-11e7-88a0-ee23c35a1e51.png)
![erro 9](https://user-images.githubusercontent.com/31859118/30554151-e98cf7ce-9c79-11e7-9eef-c16b3b0ce5ad.png)

**Comment by bmarchete** [comment]
@CampeonatoJJJE  Erro de insert é primário, acho que alguem tem que voltar pro primeiro ano fazer TLBD I ! 😕

**Comment by CampeonatoJJJE** [comment]
Pronto!! O erro foi corrigido.

**Comment by tlbdmecanica** [comment]
Ainda continua com erro, por favor tentem corrigir e verifiquem antes de enviar para nós o arquivo "Inserts.sql", algumas tabelas estão com erro
O 1º erro está em "jogadores", a tabela "codigo_time" está errada, na criação do banco de dados está "times_codigo" 

![erro 14](https://user-images.githubusercontent.com/31859118/30605865-1d242568-9d46-11e7-9442-5d0a7cf375ac.png)

O 2º erro está em "pontuacao", a tabela "codigo_campeonato" está errada, na criação do banco de dados está "campeonato_codigo" o mesmo ocorre novamente para o "codigo_times"

![erro 15](https://user-images.githubusercontent.com/31859118/30605971-76ca8026-9d46-11e7-94be-fc75c98f4498.png)

O 3º erro está em "times", a tabela "data_criação" está errada o seu formato de inserção, na criação do banco de dados está dates, e o formato padrão é "YYYY-MM-DD" e vocês colocaram no formato "MM-DD-YYYY".

![erro 12](https://user-images.githubusercontent.com/31859118/30606064-ccbaa65a-9d46-11e7-9d01-f5fa0d66addc.png)

O 4º erro está em "pontuacao", a tabela "codigo_campeonato" é "Primary key", e como vocês estão fazendo 2 inserções com o mesmo "ID", está dando que não pode criar por estar duplicando a "Primary Key".

![erro 10](https://user-images.githubusercontent.com/31859118/30606201-4692d326-9d47-11e7-86e2-cefb263ad6e8.png)

**Comment by CampeonatoJJJE** [comment]
Todos os erros foram corrigidos e devidamente testados, peço desde já desculpas pelo transtorno e espero que o resto se siga corretamente, estarei no aguardo de respostas, caso ocorra mais um erro avise-nos pois essa issue só será fechada após o seu aval.

**Comment by tlbdmecanica** [comment]
Continua com erro

**Comment by tlbdmecanica** [comment]
Continua com erros, na tabela jogadores, o "codigo_times" está inserindo emails, em vez de dados do tipo números.

**Comment by tlbdmecanica** [comment]
Erro no arquivo pontuação: está dando o seguinte erro no "insert":


![erro15](https://user-images.githubusercontent.com/31859118/30820262-c8980e90-a1f7-11e7-803f-16e824d50cd5.png)

**Comment by CampeonatoJJJE** [comment]
O erro da tabela jogadores foi corrigido. 
Há mais algum erro ?

**Comment by tlbdmecanica** [comment]
Na tabela "pontuação", a chave estrangeira "campeonato_codigo" está recebendo um valor inexistente, logo que na foreign key da tabela "campeonato" os dados inseridos só vão até 100, ou seja, vocês precisam inserir mais 400 campeonatos na tabela.

**Comment by CampeonatoJJJE** [comment]
Pronto! Arrumamos este erro, obrigado pela paciência e desculpa pela demora.
